---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Jueun Kang
  - Tayedza Chikumbirike
thanks: "Code and data are available at: https://github.com/tayedzac/GSS_education."
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---
# Introduction

# Data

## Data Source and Methodology

## Attributes

# Data (idk what to title this)
```{r}
#| include: false
#| warning: false
#| message: false

#### Read in data ####

library(tidyverse)
library(janitor)
library(tidyr)

# Respondent
clean_data_respondent <- read_csv("inputs/data/clean_data1.csv")

# Mom
clean_data_mom <- read_csv("inputs/data/clean_data2.csv")

# Dad
clean_data_dad <- read_csv("inputs/data/clean_data3.csv")

```

```{r}
#| include: false
#| warning: false
#| message: false

#### Prepare data ####

## Respondent
clean_data_respondent <-
  clean_data_respondent %>%
  mutate(
    education = fct_relevel(
      education,
      "< High School",
      "High School",
      "Some College",
      "4 Years of College",
      "> 4 years of college"
    )
  )

## Mom
clean_data_mom <-
  clean_data_mom %>%
  mutate(
    education = fct_relevel(
      education,
      "< High School",
      "High School",
      "Some College",
      "4 Years of College",
      "> 4 years of college"
    )
  )

## Dad
clean_data_dad <-
  clean_data_dad %>%
  mutate(
    education = fct_relevel(
      education,
      "< High School",
      "High School",
      "Some College",
      "4 Years of College",
      "> 4 years of college"
    )
  )

## Respondent and Mom
respondent_and_mum <- 
  clean_data_respondent %>% 
  left_join(clean_data_mom, by = join_by(id), suffix = c("Respondent", "Mom"))

## Respondent and Dad
respondent_and_dad <- 
  clean_data_respondent %>% 
  left_join(clean_data_dad, by = join_by(id), suffix = c("Respondent", "Dad"))
```


```{r}
#| label: fig-1
#| fig-cap: Highest Degree of Education Obtained by the Respondant.
#| echo: false
#| warning: false
#| message: false

clean_data_respondent |>
  ggplot(aes(x = education)) +
  geom_bar(fill = "slateblue1") +
  theme_minimal() +
  labs(x = "Highest Education Level",
       y = "Number of Participants",
       title = "Education Level of the Respondant.")
```

```{r}
#| label: fig-2
#| fig-cap: Highest Degree of Education Obtained by the Respondants' Mother.
#| echo: false
#| warning: false
#| message: false


clean_data_mom |> 
  ggplot(aes(x = education)) +
  geom_bar(fill = "violet") +
  theme_minimal() +
  labs(x = "Highest Education Level",
       y = "Number of Participants",
       title = "Education Level of Respondants' Mother.")
```

```{r}
#| label: fig-3
#| fig-cap: Highest Degree of Education Obtained by the Respondants' Father.
#| echo: false
#| warning: false
#| message: false


clean_data_dad |> 
  ggplot(aes(x = education)) +
  geom_bar(fill = "lightskyblue") +
  theme_minimal() +
  labs(x = "Highest Education Level",
       y = "Number of Participants",
       title = "Education Level of Respondants' Father.")
```




```{r}
#| label: fig-4
#| fig-cap: Comparison Between the Respondant and Mother.
#| echo: false
#| warning: false
#| message: false

## Comparison between respondent and Mom

respondent_and_mum |> 
  ggplot(aes(x = educationRespondent, y = educationMom)) +
  geom_jitter() + 
  theme_minimal() +
  labs(x = "Highest Education Level - Respondent",
       y = "Highest Education Level - Mother",
       title = "Education Level of Respondant and Mother.")
```

```{r}
#| label: fig-4
#| fig-cap: Comparison Between the Respondant and Father.
#| echo: false
#| warning: false
#| message: false

## Comparison between respondent and Dad

respondent_and_dad |> 
  ggplot(aes(x = educationRespondent, y = educationDad)) +
  geom_jitter() + 
  theme_minimal() +
  labs(x = "Highest Education Level - Respondent",
       y = "Highest Education Level - Father",
       title = "Education Level of Respondant and Father.")
```



# Results



# Discussion

# Conclusion

\newpage

# References


